name: Release

on:
  push:
    branches:
      - publish-fork

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          make release
        env:
          USE_RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - name: NPM Login to registry
        run: npm login --registry=https://npm.pkg.github.com --scope=@lewiscowles1986
      - name: Publish version
        run: npm publish --registry=https://npm.pkg.github.com --scope=@lewiscowles1986
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
